excluded:
    - Vendor
    - Pods
disabled_rules:
    - dynamic_inline
    - explicit_top_level_acl
    - explicit_type_interface
    - notification_center_detachment
    - type_body_length
    - void_return
    - protocol_property_accessors_order
    - identifier_name
    - four_spaces
    - empty_parentheses_with_trailing_closure
opt_in_rules:
    - closure_end_indentation
    - closure_spacing
    - empty_count
    - explicit_init
    - first_where
    - number_separator
    - operator_usage_whitespace
    - private_outlet
    - redundant_nil_coalescing
    - vertical_parameter_alignment_on_call
    - implicit_return
    - multiline_parameters
    - extension_access_modifier

nesting:
    type_level: 2

function_parameter_count:
    warning: 8
    error: 200

type_name:
    min_length:
        w:0
        e:0

generic_type_name:
    min_length:
        w:0
        e:0

identifier_name:
    min_length:
        w:0
        e:0

large_tuple:
    warning: 5
    error: 200

line_length:
    warning: 150
    error: 2000

file_header:
    required_pattern: |
                      \/\/
                      \/\/  .*\.swift
                      \/\/  .*?
                      \/\/
                      \/\/  Created by .* on \d{1,2}[\/\.]\d{1,2}[\/\.]\d{2}\.
                      \/\/  Copyright (©|\(c\)) \d{4} .*\. All rights reserved\.
                      \/\/

custom_rules:
    no_tabs:
        name: "Tabs are not allowed"
        message: "Do not use tabs, use 4 spaces."
        regex: "^( *)?\t"
    four_spaces:
        name: "Indent by four spaces"
        regex: "(^                                       (?! +))|(^                                   (?! +))|(^                               (?! +))|(^                           (?! +))|(^                       (?! +))|(^                   (?! +))|(^               (?! +))|(^           (?! +))|(^       (?! +))|(^   (?! +))|(^  (?! +))|(^ (?! +))"
    no_none:
        name: "Do not use .none in enums"
        regex: "case(.*,)?.none"
